import {
  Layers,
  Box,
  Play,
  Music,
  PaintBucket,
  BarChart,
  Palette,
  SlidersHorizontal,
  Layout,
  Database,
  Calendar,
  Zap,
  Code,
  Globe,
} from "lucide-react"
import type { Category, Framework } from "./types"

// Sample data based on the GitHub repository categories
export const featuredFrameworks: Framework[] = [
  {
    id: "react",
    name: "React",
    description: "A JavaScript library for building user interfaces",
    url: "https://reactjs.org",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["framework", "ui", "javascript"],
    stars: 203000,
    forks: 42000,
    category: "frontend-frameworks",
  },
  {
    id: "vue",
    name: "Vue.js",
    description: "The Progressive JavaScript Framework",
    url: "https://vuejs.org",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["framework", "ui", "javascript"],
    stars: 201000,
    forks: 33000,
    category: "frontend-frameworks",
  },
  {
    id: "svelte",
    name: "Svelte",
    description: "Cybernetically enhanced web apps",
    url: "https://svelte.dev",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["framework", "ui", "javascript"],
    stars: 68000,
    forks: 3400,
    category: "frontend-frameworks",
  },
  {
    id: "nextjs",
    name: "Next.js",
    description: "The React Framework for Production",
    url: "https://nextjs.org",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["framework", "react", "ssr"],
    stars: 103000,
    forks: 23000,
    category: "frontend-frameworks",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    description: "A utility-first CSS framework for rapid UI development",
    url: "https://tailwindcss.com",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["css", "framework", "utility"],
    stars: 68000,
    forks: 3400,
    category: "css-ui-frameworks",
  },
  {
    id: "threejs",
    name: "Three.js",
    description: "JavaScript 3D library",
    url: "https://threejs.org",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["3d", "webgl", "javascript"],
    stars: 88000,
    forks: 33000,
    category: "3d-webgl-frameworks",
  },
  {
    id: "d3",
    name: "D3.js",
    description: "Data-Driven Documents",
    url: "https://d3js.org",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["data", "visualization", "svg"],
    stars: 103000,
    forks: 22000,
    category: "charts",
  },
  {
    id: "jquery",
    name: "jQuery",
    description: "Fast, small, and feature-rich JavaScript library",
    url: "https://jquery.com",
    logo: "/placeholder.svg?height=32&width=32",
    tags: ["javascript", "dom", "utility"],
    stars: 56000,
    forks: 20000,
    category: "allrounder",
  },
]

// Create categories based on the GitHub repository structure
export const categories: Category[] = [
  {
    id: "3d-webgl-frameworks",
    name: "3D/WebGL Frameworks",
    icon: <Box className="h-5 w-5" />,
    items: [
      {
        id: "threejs",
        name: "Three.js",
        description: "JavaScript 3D library",
        url: "https://threejs.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["3d", "webgl", "javascript"],
        stars: 88000,
        forks: 33000,
        category: "3d-webgl-frameworks",
      },
      {
        id: "babylonjs",
        name: "Babylon.js",
        description: "A powerful, beautiful, simple, and open game and rendering engine",
        url: "https://www.babylonjs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["3d", "webgl", "javascript", "game-engine"],
        stars: 19000,
        forks: 3300,
        category: "3d-webgl-frameworks",
      },
      {
        id: "playcanvas",
        name: "PlayCanvas",
        description: "Fast and lightweight JavaScript game engine",
        url: "https://playcanvas.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["3d", "webgl", "javascript", "game-engine"],
        stars: 8000,
        forks: 1300,
        category: "3d-webgl-frameworks",
      },
      {
        id: "aframe",
        name: "A-Frame",
        description: "Web framework for building virtual reality experiences",
        url: "https://aframe.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["3d", "webgl", "javascript", "vr"],
        stars: 15000,
        forks: 3800,
        category: "3d-webgl-frameworks",
      },
    ],
  },
  {
    id: "allrounder",
    name: "Allrounder (jQuery like)",
    icon: <Globe className="h-5 w-5" />,
    items: [
      {
        id: "jquery",
        name: "jQuery",
        description: "Fast, small, and feature-rich JavaScript library",
        url: "https://jquery.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["javascript", "dom", "utility"],
        stars: 56000,
        forks: 20000,
        category: "allrounder",
      },
      {
        id: "zepto",
        name: "Zepto.js",
        description: "Minimalist JavaScript library for modern browsers with a jQuery-compatible API",
        url: "https://zeptojs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["javascript", "dom", "utility", "mobile"],
        stars: 15000,
        forks: 3900,
        category: "allrounder",
      },
      {
        id: "umbrella",
        name: "Umbrella JS",
        description: "Tiny library for DOM manipulation, events and AJAX",
        url: "https://umbrellajs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["javascript", "dom", "utility"],
        stars: 3500,
        forks: 200,
        category: "allrounder",
      },
      {
        id: "cash",
        name: "Cash",
        description: "An absurdly small jQuery alternative for modern browsers",
        url: "https://github.com/fabiospampinato/cash",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["javascript", "dom", "utility"],
        stars: 5000,
        forks: 300,
        category: "allrounder",
      },
    ],
  },
  {
    id: "animations",
    name: "Animations",
    icon: <Play className="h-5 w-5" />,
    items: [
      {
        id: "gsap",
        name: "GSAP",
        description: "Professional-grade animation for the modern web",
        url: "https://greensock.com/gsap/",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["animation", "javascript"],
        stars: 16000,
        forks: 1100,
        category: "animations",
      },
      {
        id: "animejs",
        name: "Anime.js",
        description: "A lightweight JavaScript animation library",
        url: "https://animejs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["animation", "javascript"],
        stars: 43000,
        forks: 3300,
        category: "animations",
      },
      {
        id: "motion",
        name: "Motion One",
        description: "A new animation library, built on the Web Animations API",
        url: "https://motion.dev",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["animation", "javascript"],
        stars: 6500,
        forks: 200,
        category: "animations",
      },
      {
        id: "popmotion",
        name: "Popmotion",
        description: "Simple animation libraries for delightful user interfaces",
        url: "https://popmotion.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["animation", "javascript"],
        stars: 19500,
        forks: 800,
        category: "animations",
      },
    ],
  },
  {
    id: "audio",
    name: "Audio",
    icon: <Music className="h-5 w-5" />,
    items: [
      {
        id: "howler",
        name: "Howler.js",
        description: "JavaScript audio library for the modern web",
        url: "https://howlerjs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["audio", "javascript"],
        stars: 20000,
        forks: 2000,
        category: "audio",
      },
      {
        id: "tone",
        name: "Tone.js",
        description: "A Web Audio framework for making interactive music in the browser",
        url: "https://tonejs.github.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["audio", "javascript", "music"],
        stars: 12000,
        forks: 1200,
        category: "audio",
      },
      {
        id: "wavesurfer",
        name: "wavesurfer.js",
        description: "Navigable waveform built on Web Audio and Canvas",
        url: "https://wavesurfer-js.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["audio", "javascript", "visualization"],
        stars: 6500,
        forks: 1300,
        category: "audio",
      },
      {
        id: "pizzicato",
        name: "Pizzicato.js",
        description: "A library that simplifies the way you create and manipulate sounds with the Web Audio API",
        url: "https://alemangui.github.io/pizzicato/",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["audio", "javascript"],
        stars: 2500,
        forks: 300,
        category: "audio",
      },
    ],
  },
  {
    id: "canvas-svg",
    name: "Canvas and SVG",
    icon: <PaintBucket className="h-5 w-5" />,
    items: [
      {
        id: "paper",
        name: "Paper.js",
        description: "The Swiss Army Knife of Vector Graphics Scripting",
        url: "http://paperjs.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["canvas", "svg", "vector-graphics"],
        stars: 13000,
        forks: 1700,
        category: "canvas-svg",
      },
      {
        id: "fabric",
        name: "Fabric.js",
        description: "Javascript Canvas Library, SVG-to-Canvas Parser",
        url: "http://fabricjs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["canvas", "svg", "interactive"],
        stars: 22000,
        forks: 3200,
        category: "canvas-svg",
      },
      {
        id: "snap",
        name: "Snap.svg",
        description: "The JavaScript library for modern SVG graphics",
        url: "http://snapsvg.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["svg", "vector-graphics"],
        stars: 8700,
        forks: 1300,
        category: "canvas-svg",
      },
      {
        id: "two",
        name: "Two.js",
        description: "A renderer agnostic two-dimensional drawing api for the web",
        url: "https://two.js.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["canvas", "svg", "webgl"],
        stars: 7800,
        forks: 600,
        category: "canvas-svg",
      },
    ],
  },
  {
    id: "charts",
    name: "Charts",
    icon: <BarChart className="h-5 w-5" />,
    items: [
      {
        id: "d3",
        name: "D3.js",
        description: "Data-Driven Documents",
        url: "https://d3js.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["data", "visualization", "svg"],
        stars: 103000,
        forks: 22000,
        category: "charts",
      },
      {
        id: "chartjs",
        name: "Chart.js",
        description: "Simple yet flexible JavaScript charting for designers & developers",
        url: "https://www.chartjs.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["charts", "canvas", "responsive"],
        stars: 59000,
        forks: 11000,
        category: "charts",
      },
      {
        id: "echarts",
        name: "ECharts",
        description: "An Open Source JavaScript Visualization Library",
        url: "https://echarts.apache.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["charts", "visualization", "canvas"],
        stars: 53000,
        forks: 19000,
        category: "charts",
      },
      {
        id: "highcharts",
        name: "Highcharts",
        description: "Interactive JavaScript charts for your web pages",
        url: "https://www.highcharts.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["charts", "interactive", "svg"],
        stars: 11000,
        forks: 3000,
        category: "charts",
      },
    ],
  },
  {
    id: "colors",
    name: "Colors",
    icon: <Palette className="h-5 w-5" />,
    items: [
      {
        id: "chroma",
        name: "Chroma.js",
        description: "JavaScript library for all kinds of color manipulations",
        url: "https://gka.github.io/chroma.js/",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["color", "manipulation"],
        stars: 9000,
        forks: 600,
        category: "colors",
      },
      {
        id: "colorjs",
        name: "Color.js",
        description: "A color manipulation library that works with a wide variety of color spaces",
        url: "https://colorjs.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["color", "manipulation"],
        stars: 1500,
        forks: 100,
        category: "colors",
      },
      {
        id: "tinycolor",
        name: "TinyColor",
        description: "Fast, small color manipulation and conversion for JavaScript",
        url: "https://github.com/bgrins/TinyColor",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["color", "manipulation"],
        stars: 4000,
        forks: 500,
        category: "colors",
      },
      {
        id: "colord",
        name: "colord",
        description: "A tiny yet powerful tool for high-performance color manipulations and conversions",
        url: "https://github.com/omgovich/colord",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["color", "manipulation"],
        stars: 3500,
        forks: 150,
        category: "colors",
      },
    ],
  },
  {
    id: "content-slider",
    name: "Content Slider/Carousels",
    icon: <SlidersHorizontal className="h-5 w-5" />,
    items: [
      {
        id: "swiper",
        name: "Swiper",
        description: "Most modern mobile touch slider with hardware accelerated transitions",
        url: "https://swiperjs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["slider", "carousel", "touch"],
        stars: 33000,
        forks: 9800,
        category: "content-slider",
      },
      {
        id: "splide",
        name: "Splide",
        description: "A lightweight, flexible and accessible slider/carousel",
        url: "https://splidejs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["slider", "carousel", "accessible"],
        stars: 6500,
        forks: 500,
        category: "content-slider",
      },
      {
        id: "glide",
        name: "Glide.js",
        description: "A dependency-free JavaScript ES6 slider and carousel",
        url: "https://glidejs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["slider", "carousel"],
        stars: 6800,
        forks: 1100,
        category: "content-slider",
      },
      {
        id: "embla",
        name: "Embla Carousel",
        description: "A lightweight carousel library with fluid motion and great swipe precision",
        url: "https://www.embla-carousel.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["slider", "carousel", "touch"],
        stars: 4500,
        forks: 300,
        category: "content-slider",
      },
    ],
  },
  {
    id: "css-ui-frameworks",
    name: "CSS/UI Frameworks",
    icon: <Layout className="h-5 w-5" />,
    items: [
      {
        id: "tailwindcss",
        name: "Tailwind CSS",
        description: "A utility-first CSS framework for rapid UI development",
        url: "https://tailwindcss.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["css", "framework", "utility"],
        stars: 68000,
        forks: 3400,
        category: "css-ui-frameworks",
      },
      {
        id: "bootstrap",
        name: "Bootstrap",
        description:
          "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile-first websites",
        url: "https://getbootstrap.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["css", "framework", "responsive"],
        stars: 160000,
        forks: 78000,
        category: "css-ui-frameworks",
      },
      {
        id: "bulma",
        name: "Bulma",
        description: "Modern CSS framework based on Flexbox",
        url: "https://bulma.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["css", "framework", "flexbox"],
        stars: 46000,
        forks: 3800,
        category: "css-ui-frameworks",
      },
      {
        id: "unocss",
        name: "UnoCSS",
        description: "The instant on-demand atomic CSS engine",
        url: "https://unocss.dev",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["css", "framework", "utility"],
        stars: 12000,
        forks: 700,
        category: "css-ui-frameworks",
      },
    ],
  },
  {
    id: "databases-storage",
    name: "Databases/Storage",
    icon: <Database className="h-5 w-5" />,
    items: [
      {
        id: "pouchdb",
        name: "PouchDB",
        description: "A pocket-sized database that runs in the browser",
        url: "https://pouchdb.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["database", "offline", "sync"],
        stars: 15000,
        forks: 1400,
        category: "databases-storage",
      },
      {
        id: "dexie",
        name: "Dexie.js",
        description: "A Minimalistic Wrapper for IndexedDB",
        url: "https://dexie.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["database", "indexeddb"],
        stars: 8500,
        forks: 600,
        category: "databases-storage",
      },
      {
        id: "localforage",
        name: "localForage",
        description: "Offline storage, improved. Wraps IndexedDB, WebSQL, or localStorage",
        url: "https://localforage.github.io/localForage/",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["storage", "offline"],
        stars: 21000,
        forks: 1200,
        category: "databases-storage",
      },
      {
        id: "rxdb",
        name: "RxDB",
        description: "A realtime Database for JavaScript Applications",
        url: "https://rxdb.info",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["database", "realtime", "offline"],
        stars: 18000,
        forks: 900,
        category: "databases-storage",
      },
    ],
  },
  {
    id: "dates",
    name: "Dates",
    icon: <Calendar className="h-5 w-5" />,
    items: [
      {
        id: "dayjs",
        name: "Day.js",
        description: "Fast 2kB alternative to Moment.js with the same modern API",
        url: "https://day.js.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["date", "time"],
        stars: 41000,
        forks: 2000,
        category: "dates",
      },
      {
        id: "date-fns",
        name: "date-fns",
        description: "Modern JavaScript date utility library",
        url: "https://date-fns.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["date", "time", "immutable"],
        stars: 30000,
        forks: 1500,
        category: "dates",
      },
      {
        id: "luxon",
        name: "Luxon",
        description: "A library for working with dates and times in JavaScript",
        url: "https://moment.github.io/luxon/",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["date", "time"],
        stars: 13000,
        forks: 700,
        category: "dates",
      },
      {
        id: "moment",
        name: "Moment.js",
        description: "Parse, validate, manipulate, and display dates in javascript",
        url: "https://momentjs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["date", "time"],
        stars: 46000,
        forks: 7000,
        category: "dates",
      },
    ],
  },
  {
    id: "events",
    name: "Events",
    icon: <Zap className="h-5 w-5" />,
    items: [
      {
        id: "mitt",
        name: "mitt",
        description: "Tiny 200 byte functional event emitter / pubsub",
        url: "https://github.com/developit/mitt",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["events", "pubsub"],
        stars: 9000,
        forks: 400,
        category: "events",
      },
      {
        id: "eventemitter3",
        name: "EventEmitter3",
        description: "A high performance EventEmitter",
        url: "https://github.com/primus/eventemitter3",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["events", "pubsub"],
        stars: 2500,
        forks: 200,
        category: "events",
      },
      {
        id: "nanoevents",
        name: "nanoevents",
        description: "Simple and tiny event emitter library for JavaScript",
        url: "https://github.com/ai/nanoevents",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["events", "pubsub"],
        stars: 1800,
        forks: 100,
        category: "events",
      },
      {
        id: "tiny-emitter",
        name: "tiny-emitter",
        description: "A tiny (less than 1k) event emitter library",
        url: "https://github.com/scottcorgan/tiny-emitter",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["events", "pubsub"],
        stars: 1300,
        forks: 100,
        category: "events",
      },
    ],
  },
  {
    id: "frontend-frameworks",
    name: "Frontend Frameworks/UI Component Libraries",
    icon: <Layers className="h-5 w-5" />,
    items: [
      {
        id: "react",
        name: "React",
        description: "A JavaScript library for building user interfaces",
        url: "https://reactjs.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["framework", "ui", "javascript"],
        stars: 203000,
        forks: 42000,
        category: "frontend-frameworks",
      },
      {
        id: "vue",
        name: "Vue.js",
        description: "The Progressive JavaScript Framework",
        url: "https://vuejs.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["framework", "ui", "javascript"],
        stars: 201000,
        forks: 33000,
        category: "frontend-frameworks",
      },
      {
        id: "svelte",
        name: "Svelte",
        description: "Cybernetically enhanced web apps",
        url: "https://svelte.dev",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["framework", "ui", "javascript"],
        stars: 68000,
        forks: 3400,
        category: "frontend-frameworks",
      },
      {
        id: "angular",
        name: "Angular",
        description: "Platform for building mobile and desktop web applications",
        url: "https://angular.io",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["framework", "typescript", "google"],
        stars: 86000,
        forks: 22000,
        category: "frontend-frameworks",
      },
    ],
  },
  {
    id: "general",
    name: "General",
    icon: <Code className="h-5 w-5" />,
    items: [
      {
        id: "lodash",
        name: "Lodash",
        description: "A modern JavaScript utility library delivering modularity, performance & extras",
        url: "https://lodash.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["utility", "functional"],
        stars: 55000,
        forks: 6800,
        category: "general",
      },
      {
        id: "ramda",
        name: "Ramda",
        description: "A practical functional library for JavaScript programmers",
        url: "https://ramdajs.com",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["utility", "functional"],
        stars: 22000,
        forks: 1700,
        category: "general",
      },
      {
        id: "underscore",
        name: "Underscore",
        description: "JavaScript's utility _ belt",
        url: "https://underscorejs.org",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["utility", "functional"],
        stars: 26000,
        forks: 5700,
        category: "general",
      },
      {
        id: "immer",
        name: "Immer",
        description: "Create the next immutable state by mutating the current one",
        url: "https://immerjs.github.io/immer/",
        logo: "/placeholder.svg?height=32&width=32",
        tags: ["immutable", "state"],
        stars: 25000,
        forks: 800,
        category: "general",
      },
    ],
  },
]

